name = "pcvct"
uuid = "3c374bc7-7384-4f83-8ca0-87b8c727e6ff"
authors = ["Daniel Bergman <danielrbergman@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
