name: CI_test
on:
  push:
    branches:
      - main
      - development
      - feature-tests
            
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download PhysiCell
        run: |
          python ./tests/get_my_physicell.py
          unzip -q PhysiCell-my-physicell.zip -d ./tests
          echo "PhysiCell downloaded, unzipped, and moved to ./tests/PhysiCell"
      - name: Set up test project
        run: |
          mv ./tests/PhysiCell-my-physicell ./tests/PhysiCell
          mkdir -p ./tests/test-project/data/inputs/configs/default
          cp ./tests/PhysiCell/sample_projects/template/config/PhysiCell_settings.xml ./tests/test-project/data/inputs/configs/default/PhysiCell_settings.xml
          mkdir -p ./tests/test-project/data/inputs/custom_codes/default
          cp ./tests/PhysiCell/sample_projects/template/main.cpp ./tests/test-project/data/inputs/custom_codes/default/main.cpp
          cp -r ./tests/PhysiCell/sample_projects/template/custom_modules ./tests/test-project/data/inputs/custom_codes/default/custom_modules
          mkdir -p ./tests/test-project/data/inputs/rulesets_collections/default
          touch ./tests/test-project/data/inputs/rulesets_collections/default/base_rulesets.csv
          echo "default,pressure,decreases,cycle entry,0,0.5,4,0" >> ./tests/test-project/data/inputs/rulesets_collections/default/base_rulesets.csv
          echo "Template project files are in place within ./tests/test-project/data/inputs"
      - name: Initialize database
        run: |
          cd ./tests
          julia ./test-project/VCT/InitializeDatabase.jl
          echo "Database initialized"